#!/bin/sh
#
# chkconfig: 345 87 08
# description: Squid Account Management System (SAMS)
#
# Source function library.
. /etc/init.d/functions

SAMSPATH=`cat /etc/sams.conf | grep SAMSPATH | tr "SAMSPATH=" "\0"`
EXE=$SAMSPATH/bin/samsdaemon
LOCKFILE=/var/lock/samsd
RETVAL=0

start()
{
	echo -n "Starting samsd: "
	daemon "$EXE" 
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch "$LOCKFILE"
        echo
}

stop()
{
	echo -n "Shutting down samsd: "
	killproc "$EXE"
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f "$LOCKFILE"
        echo
}

restart()
{
	stop
	start
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	reload)
		echo "Sams not implemented command yet"
		;;
	status)
	        status "$EXE"
		;;
	*)
		echo "Usage: ${0##*/} {start|stop|restart}"
		RETVAL=1
esac

exit $RETVAL
