Document: sams
Title: Debian sams Manual
Author: <insert document author here>
Abstract: This manual describes what sams is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sams/sams.sgml.gz

Format: postscript
Files: /usr/share/doc/sams/sams.ps.gz

Format: text
Files: /usr/share/doc/sams/sams.text.gz

Format: HTML
Index: /usr/share/doc/sams/html/index.html
Files: /usr/share/doc/sams/html/*.html

  
